pm25:
  - {c_low: 0.0, c_high: 9.0, i_low: 0, i_high: 50}
  - {c_low: 9.1, c_high: 35.4, i_low: 51, i_high: 100}
  - {c_low: 35.5, c_high: 55.4, i_low: 101, i_high: 150}
  - {c_low: 55.5, c_high: 125.4, i_low: 151, i_high: 200}
  - {c_low: 125.5, c_high: 225.4, i_low: 201, i_high: 300}
  - {c_low: 225.5, c_high: 500.4, i_low: 301, i_high: 500}
