cluster_0: "Ngày rất trong lành"
cluster_1: "Ngày ô nhiễm nhẹ"
cluster_2: "Ngày ô nhiễm trung bình"
cluster_3: "Ngày cực kỳ ô nhiễm"
cluster_4: "Bất thường cục bộ"
cluster_5: "Dông lốc cát"
cluster_6: "Cháy rừng"
cluster_7: "Không xác định"
